### ISSUE TITLE
Password and hash save in one txt file

### ISSUE THREAD

**Issue by qemboo** [amirrezaes/Pyrunch#1]
Hey want to ask if you can change it so that you can also save password and hash in a text file please :) 

Example Text file
0001 = 888b19a43b151683c87895f6211d9f8640f97bdc8ef32f03dbe057c8f5e56d32
0002 = 4fac6dbe26e823ed6edf999c63fab3507119cf3cbfb56036511aa62e258c35b4
0003 = 446e21f212ab200933c4c9a0802e1ff0c410bbd75fca10168746fc49883096db

**Comment by amirrezaes** [comment]
Sure
I added --combo option which takes an argument as separator, use quotation if your separator will include spaces.

Example:
pyrunch.py 1 2 12 --combo " = " --hash sha256

  1 = 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b
  2 = d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35
11 = 4fc82b26aecb47d2868c4efbe3581732a3e7cbcc6c2efb32062c08170a05eeb8
12 = 6b51d431df5d7f141cbececcf79edf3dd861c3b4069f0b11661a3eefacbba918
21 = 6f4b6612125fb3a0daecd2799dfd6c9c299424fd920f9b308110a2c1fbd8f443
22 = 785f3ec7eb32f30b90cd0fcf3657d388b5ff4297f2f9716ff66e9b69c05ddd09

**Comment by qemboo** [comment]
thx :)

I enter the same as you pyrunch.py 1 2 12 --combo " = " --hash sha256
but by me write it?

16b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b
2d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35
114fc82b26aecb47d2868c4efbe3581732a3e7cbcc6c2efb32062c08170a05eeb8
126b51d431df5d7f141cbececcf79edf3dd861c3b4069f0b11661a3eefacbba918
216f4b6612125fb3a0daecd2799dfd6c9c299424fd920f9b308110a2c1fbd8f443
22785f3ec7eb32f30b90cd0fcf3657d388b5ff4297f2f9716ff66e9b69c05ddd09

**Comment by amirrezaes** [comment]
Fixed it

**Comment by qemboo** [comment]
thank you very much it works :)
